export default {
    ACCOUNT_SIGN_IN:   'ACCOUNT_SIGN_IN',
    ACCOUNT_SIGN_OUT:  'ACCOUNT_SIGN_OUT',
    ACCOUNT_CREATED:      'ACCOUNT_CREATED',
    GET_USER:           'GET_USER',
    ROLES_RECEIVED:     'ROLES_RECEIVED',
    
    COURSES_FETCHED: 'COURSES_FETCHED',
    COURSE_FETCHED: 'COURSES_FETCHED',
    COURSE_UPDATED: 'COURSE_UPDATED',
    COURSE_DELETED: 'COURSE_UPDATED',
    COURSE_ADDED: 'COURSE_UPDATED',

    USERS_FETCHED: 'USERS_FETCHED',
    USER_UPDATED: 'USER_UPDATED',
    USER_DELETED: 'USER_DELETED',

    CLASSES_FETCHED: 'CLASSES_FETCHED',
    CLASS_CREATED: 'CLASS_CREATED',
    CLASS_FETCHED: 'CLASS_FETCHED',
    CLASS_STUDENTS_FETCHED: 'CLASS_STUDENTS_FETCHED',
    CLASS_INS_FETCHED: 'CLASS_INS_FETCHED',
    CLASS_STUDENT_ADDED: 'CLASS_STUDENT_ADDED',
    CLASS_INS_ADDED:'CLASS_INS_ADDED',
    CLASS_STUDENT_REMOVED:'CLASS_STUDENT_REMOVED',
    CLASS_INS_REMOVED:'CLASS_INS_REMOVED',


    EXAMS_FETCHED:'EXAMS_FETCHED',
    EXAM_CREATED:'EXAM_CREATED',
    EXAMS_DELETED:'EXAMS_DELETED',
    EXAM_FETCHED: 'EXAM_FETCHED',
    EXAM_UPDATED: 'EXAM_UPDATED',
}